//! Restart-stable agent identity. Hosts may reuse an existing UUID handle.

use std::fmt;

const AGENT_PREFIX: &str = "ag1.";
const ATTEMPT_PREFIX: &str = "at1.";
const UUID_TOKEN_LEN: usize = 36;
const UUID_HYPHENS: [usize; 4] = [8, 13, 18, 23];
const UUID_V7_INDEX: usize = 14;
const UUID_VARIANT_INDEX: usize = 19;

/// Opaque logical agent name. Survives restart and is distinct from delivery addresses.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct AgentId(String);

impl AgentId {
    /// Host supplies entropy. Core does not keep a process-global counter.
    #[must_use]
    pub fn mint(entropy: u128) -> Self {
        Self(format!("{AGENT_PREFIX}{entropy:x}"))
    }

    /// Adopt a presented opaque token. Does not mint.
    #[must_use]
    pub fn parse(token: &str) -> Option<Self> {
        let token = token.trim();
        if is_uuid_v7(token) {
            return Some(Self(token.to_owned()));
        }
        parse_prefixed(token, AGENT_PREFIX).map(Self)
    }

    /// Adopt a UUIDv7 generated by the host. Does not mint.
    #[must_use]
    pub fn from_uuid_v7(token: impl Into<String>) -> Option<Self> {
        let token = token.into();
        is_uuid_v7(&token).then_some(Self(token))
    }

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl AsRef<str> for AgentId {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl fmt::Display for AgentId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// One activation of an [`AgentId`]. A resume or fork always mints a new one.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct AttemptId(String);

impl AttemptId {
    /// Host supplies entropy. Core does not keep a process-global counter.
    #[must_use]
    pub fn mint(entropy: u128) -> Self {
        Self(format!("{ATTEMPT_PREFIX}{entropy:x}"))
    }

    /// Adopt a presented opaque token. Does not mint.
    #[must_use]
    pub fn parse(token: &str) -> Option<Self> {
        parse_prefixed(token, ATTEMPT_PREFIX).map(Self)
    }

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl AsRef<str> for AttemptId {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl fmt::Display for AttemptId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// How the next activation relates to a previous logical agent.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum IdentityAction {
    /// No previous agent. New agent and new attempt.
    Start { agent: AgentId, attempt: AttemptId },
    /// Same agent, new attempt.
    Resume { agent: AgentId, attempt: AttemptId },
    /// New agent and new attempt, branched from a previous agent.
    Fork { agent: AgentId, attempt: AttemptId },
}

/// No previous agent is always [`IdentityAction::Start`], even if `fork` is set.
#[must_use]
pub fn next_identity(
    previous: Option<&AgentId>,
    fork: bool,
    agent_entropy: u128,
    attempt_entropy: u128,
) -> IdentityAction {
    let attempt = AttemptId::mint(attempt_entropy);
    match previous {
        None => IdentityAction::Start {
            agent: AgentId::mint(agent_entropy),
            attempt,
        },
        Some(_) if fork => IdentityAction::Fork {
            agent: AgentId::mint(agent_entropy),
            attempt,
        },
        Some(agent) => IdentityAction::Resume {
            agent: agent.clone(),
            attempt,
        },
    }
}

fn is_uuid_v7(token: &str) -> bool {
    token.len() == UUID_TOKEN_LEN
        && token.bytes().enumerate().all(|(index, byte)| {
            if UUID_HYPHENS.contains(&index) {
                byte == b'-'
            } else {
                matches!(byte, b'0'..=b'9' | b'a'..=b'f')
            }
        })
        && token.as_bytes()[UUID_V7_INDEX] == b'7'
        && matches!(
            token.as_bytes()[UUID_VARIANT_INDEX],
            b'8' | b'9' | b'a' | b'b'
        )
}

fn parse_prefixed(token: &str, prefix: &str) -> Option<String> {
    let token = token.trim();
    let rest = token.strip_prefix(prefix)?;
    if rest.is_empty()
        || !rest
            .bytes()
            .all(|byte| matches!(byte, b'0'..=b'9' | b'a'..=b'f'))
    {
        return None;
    }
    Some(token.to_owned())
}

#[cfg(test)]
#[path = "identity_tests.rs"]
mod tests;
