use super::*;

/// Returns true if the prompt_id was generated by the shell for a server-initiated auto-wake turn (background task or subagent completion).
pub(crate) fn is_server_initiated_prompt(prompt_id: &str) -> bool {
    xai_grok_shell::session::PromptOrigin::from_prompt_id(prompt_id).is_synthetic()
}

/// Returns true if the prompt_id is a scheduled-task (`/loop`) fire.
/// Unlike wake turns they run through `MvpAgent::prompt()` and emit the `x.ai/session/prompt_complete` turn-end signal.
/// That exit is why a viewer can enter `TurnRunning` for them without stranding, and why the dashboard shows a running `/loop` session as Working.
pub(crate) fn is_scheduler_fired_prompt(prompt_id: &str) -> bool {
    matches!(
        xai_grok_shell::session::PromptOrigin::from_prompt_id(prompt_id),
        xai_grok_shell::session::PromptOrigin::SchedulerFired
    )
}

/// Decides which replayed turns close without a terminal marker.
/// A wake stays markerless when it streamed nothing visible or when it errored, matching live.
/// A direct-bash turn keeps its marker only for cancel and error, matching live.
pub(crate) fn suppress_replay_marker_for_origin(
    is_direct_bash: bool,
    had_visible_output: bool,
    prompt_id: &str,
    stop: crate::app::turn_completion::TurnStopReason,
) -> bool {
    if is_direct_bash {
        return matches!(stop, crate::app::turn_completion::TurnStopReason::EndTurn);
    }
    if is_wake_prompt(prompt_id) {
        return matches!(stop, crate::app::turn_completion::TurnStopReason::Error)
            || !had_visible_output;
    }
    is_server_initiated_prompt(prompt_id) && !is_scheduler_fired_prompt(prompt_id)
}

/// Builds the failure row for a wake turn that hit a rate limit after streaming visible output.
/// Shared by live `finish_wake_turn`, the arm that handles a wake terminal while a local turn is busy, and replay.
pub(super) fn rate_limited_wake_failure_event(
    agent_result: Option<&str>,
    elapsed: Option<std::time::Duration>,
) -> crate::scrollback::blocks::SessionEvent {
    crate::scrollback::blocks::SessionEvent::TurnFailed {
        error: agent_result
            .map(str::to_string)
            .unwrap_or_else(|| "rate limited".to_string()),
        elapsed,
    }
}

/// Returns true for the auto-wake turn families (`task-completed-…`, `subagent-completed-…`, `workflow-completed-…`, `notifications-…`).
/// These run non-adopted: no `PromptResponse`, no viewer finalize.
/// Their durable `TurnCompleted` is the only signal that the session went back to idle.
pub(crate) fn is_wake_prompt(prompt_id: &str) -> bool {
    matches!(
        xai_grok_shell::session::PromptOrigin::from_prompt_id(prompt_id),
        xai_grok_shell::session::PromptOrigin::TaskCompleted { .. }
            | xai_grok_shell::session::PromptOrigin::SubagentCompleted { .. }
            | xai_grok_shell::session::PromptOrigin::WorkflowCompleted { .. }
            | xai_grok_shell::session::PromptOrigin::ParentAgentMessage { .. }
            | xai_grok_shell::session::PromptOrigin::ParentHumanMessage { .. }
            | xai_grok_shell::session::PromptOrigin::NotificationDrain
    )
}

/// That is safe only when the turn will emit a terminal `x.ai/session/prompt_complete`, the only non-interactive way a viewer leaves `TurnRunning`.
/// Actor-run synthetic turns never do, so adopting one strands the viewer in `TurnRunning`.
/// This guard reads only the prompt id.
pub(crate) fn should_adopt_running_prompt(prompt_id: &str) -> bool {
    !is_server_initiated_prompt(prompt_id) || is_scheduler_fired_prompt(prompt_id)
}

/// `TurnCancelling` with no id, or this id, stays cancelling. Ended and superseded ids do not replace the current turn.
/// A command in flight is left alone. Returns false when the update belongs to a turn that already ended.
/// `turn_start_ms` is this chunk's `turnStartMs`, not the view's stamp.
pub(super) fn note_child_live_prompt(
    child: &mut AgentView,
    prompt_id: Option<&str>,
    turn_start_ms: Option<i64>,
    is_replay: bool,
) -> bool {
    if is_replay || child.session.loading_replay {
        return true;
    }
    let prompt_id = prompt_id.filter(|pid| !pid.is_empty());
    // Same start as the closed nameless turn. A late id matches while the
    // stored prompt is still None; that id is recorded so a later prompt does not.
    let is_closed_turn = child
        .unidentified_child_turn_closed_ms
        .is_some_and(|closed_start| {
            let closed_pid = child.unidentified_child_turn_closed_prompt.as_deref();
            turn_start_ms == Some(closed_start)
                && (closed_pid.is_none() || prompt_id.is_none() || closed_pid == prompt_id)
        });
    if is_closed_turn {
        if let Some(pid) = prompt_id {
            child.ended_child_prompt_ids.insert(pid.to_owned());
            if child.unidentified_child_turn_closed_prompt.is_none() {
                child.unidentified_child_turn_closed_prompt = Some(pid.to_owned());
            }
        }
        return false;
    }
    let Some(pid) = prompt_id else {
        // A nameless leftover keeps the previous turn's start. Once a named
        // prompt owns the clock, applying it restamps that anchor and lands
        // the rows on the follow-up.
        if let (Some(chunk_start), Some(live_pid)) =
            (turn_start_ms, child.session.current_prompt_id.as_deref())
            && child.turn_start_ms_prompt.as_deref() == Some(live_pid)
            && child.turn_start_ms.is_some_and(|live| live != chunk_start)
        {
            return false;
        }
        return true;
    };
    if child.ended_child_prompt_ids.contains(pid) || child.superseded_child_prompt_ids.contains(pid)
    {
        return false;
    }
    if child.session.state.command_in_flight().is_some() {
        return true;
    }
    let same = child.session.current_prompt_id.as_deref() == Some(pid);
    let missing = child.session.current_prompt_id.is_none();
    if matches!(child.session.state, AgentState::TurnCancelling) {
        if !same {
            adopt_child_prompt_id(child, pid);
        }
        if same || missing {
            return true;
        }
        child.session.state = AgentState::TurnRunning;
        return true;
    }
    if !same {
        adopt_child_prompt_id(child, pid);
    }
    if !child.session.state.is_turn_running() {
        child.session.state = AgentState::TurnRunning;
    }
    true
}

fn adopt_child_prompt_id(child: &mut AgentView, pid: &str) {
    if let Some(prev) = child.session.current_prompt_id.replace(pid.to_string())
        && prev != pid
    {
        child.superseded_child_prompt_ids.insert(prev);
        // Later updates for `prev` are dropped. Finish its rows now; the terminal still pushes the marker.
        child.session.tracker.finish_turn(&mut child.scrollback);
        child.scrollback.finish_all_running();
    }
    child.turn_started_at = None;
}

pub(super) fn backdate_child_turn_clock(child: &mut AgentView) {
    if child.turn_started_at.is_some() {
        return;
    }
    let Some(pid) = child.session.current_prompt_id.as_deref() else {
        return;
    };
    if child.turn_start_ms_prompt.as_deref() != Some(pid) {
        return;
    }
    let Some(start_ms) = child.turn_start_ms else {
        return;
    };
    child.turn_started_at = Some(viewer_turn_anchor(Some(start_ms)));
}

/// Compute the monotonic anchor a viewer should use as its turn-start time.
/// A viewer adopts the driver's turn mid-stream, so stamping `Instant::now()` would undercount elapsed by the wait for the first delta.
/// Falls back to `now` when `turnStartMs` is absent (older shell) or the wall clock is skewed forward.
pub(super) fn viewer_turn_anchor(turn_start_ms: Option<i64>) -> std::time::Instant {
    let now = std::time::Instant::now();
    let Some(start_ms) = turn_start_ms else {
        return now;
    };
    let elapsed_ms = chrono::Utc::now()
        .timestamp_millis()
        .saturating_sub(start_ms);
    if elapsed_ms <= 0 {
        return now;
    }
    now.checked_sub(std::time::Duration::from_millis(elapsed_ms as u64))
        .unwrap_or(now)
}

/// Wire fields of the wake turn's terminal signal.
/// `cancel_trigger` is `_meta.cancelTrigger`: `"send_now"` marks an internal cancel-and-send, so the `TurnCancelled` marker is suppressed.
/// The wire trigger wins; `expect_send_now_cancel` is the fallback for older shells.
pub(super) struct WakeTerminal<'a> {
    pub stop_reason: &'a str,
    pub agent_result: Option<&'a str>,
    pub cancel_trigger: Option<&'a str>,
    pub cancellation_category: Option<&'a str>,
}

/// Errored wakes close like a success (no scrollback row); the trace log is their only record.
pub(super) fn log_failed_wake(prompt_id: &str, agent_result: Option<&str>, rail: &str) {
    tracing::info!(
        prompt_id,
        rail,
        reason = agent_result.unwrap_or("unknown error"),
        "background wake turn failed; closing without a marker"
    );
}

/// Close out a wake turn. This is the only place that flushes its streamed entries still in flight, because wake turns skip `PromptResponse`.
/// An errored wake closes silently (see [`log_failed_wake`]); a chatty rate-limited wake keeps its upgrade-URL row.
/// The `HookAnnotation` warning attributes the deny but is not turn output, so a silently blocked wake closes without a marker.
/// Returns true when the wake closed with a visible `TurnCompleted` marker (chatty EndTurn).
pub(super) fn finish_wake_turn(
    agent: &mut AgentView,
    prompt_id: &str,
    terminal: WakeTerminal<'_>,
) -> bool {
    let WakeTerminal {
        stop_reason,
        agent_result,
        cancel_trigger,
        cancellation_category,
    } = terminal;

    let had_output = agent.session.tracker.output_since_last_finish();
    agent.session.tracker.finish_turn(&mut agent.scrollback);
    // The stored `turn_start_ms` may belong to an earlier turn: a silent wake streamed no deltas of its own, and interleaved deltas can re-stamp it
    // Claim an elapsed only when the anchor is provably this wake's
    let anchor_is_ours = agent.turn_start_ms_prompt.as_deref() == Some(prompt_id);
    let elapsed = if had_output && anchor_is_ours {
        agent.turn_start_ms.and_then(|start_ms| {
            let ms = chrono::Utc::now()
                .timestamp_millis()
                .saturating_sub(start_ms);
            (ms >= 0).then(|| std::time::Duration::from_millis(ms as u64))
        })
    } else {
        None
    };
    // The wire trigger decides when present; the fallback only compares `expect_send_now_cancel` and must not take or clear it
    let send_now_cancel = match cancel_trigger {
        Some(trigger) => trigger == "send_now",
        None => agent.expect_send_now_cancel.as_deref() == Some(prompt_id),
    };
    let already_failed = agent.failed_wake_marker_for.as_deref() == Some(prompt_id);
    let elapsed_ms = crate::app::turn_completion::duration_to_elapsed_ms(elapsed);
    let event = match stop_reason {
        "error" => {
            if !already_failed {
                agent.failed_wake_marker_for = Some(prompt_id.to_string());
                log_failed_wake(prompt_id, agent_result, "idle");
            }
            None
        }
        "rate_limit" if already_failed || !had_output => None,
        "rate_limit" => {
            agent.failed_wake_marker_for = Some(prompt_id.to_string());
            if crate::app::dispatch::scrollback_has_recent_error_banner(&agent.scrollback) {
                None
            } else {
                Some(rate_limited_wake_failure_event(agent_result, elapsed))
            }
        }
        // Silent wakes stay markerless; `terminal_marker` below cannot see the turn's origin, so skip it here
        _ if !had_output => None,
        _ => crate::app::turn_completion::terminal_marker(
            crate::app::turn_completion::TerminalMarkerInput {
                stop: crate::app::turn_completion::TurnStopReason::from(stop_reason),
                elapsed_ms,
                agent_result,
                send_now_cancel,
                cancel_trigger,
                cancellation_category,
                // The error arm above closed silently, so this Error arm is unreachable
                error_kind: None,
                error_banner_present: false,
            },
        ),
    };
    let notify = matches!(&event, Some(SessionEvent::TurnCompleted { .. }));
    crate::app::turn_completion::push_turn_terminal_marker(agent, event);
    crate::app::turn_completion::note_hook_blocked_turn(
        agent,
        Some(prompt_id),
        cancellation_category,
        None,
    );
    notify
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parent_message_is_non_adopted_actor_turn() {
        let prompt_id = "parent-message-msg-123";
        assert!(is_server_initiated_prompt(prompt_id));
        assert!(is_wake_prompt(prompt_id));
        assert!(!should_adopt_running_prompt(prompt_id));
    }
}
