//! Isolated on-disk foundation for the v2 memory pipeline.
//!
//! V2 never reads from or writes to the legacy `memory/` tree. Each global or
//! workspace scope owns its topics, immutable observation inbox, archive,
//! generated manifest, durable state database, and lexical index.

use std::io::{Read as _, Write as _};
use std::path::{Path, PathBuf};

use rusqlite::params;
use xai_grok_tools::util::truncate_str;
use xai_sqlite_journal::JournalMode;

const STATE_SCHEMA_VERSION: &str = "1";
const MAX_DISCOVERED_FILES: usize = 10_000;
const MAX_DIRECTORY_ENTRIES: usize = 100_000;
const MAX_MANIFEST_BYTES: usize = 16 * 1024;
const MAX_MANIFEST_ENTRIES: usize = 512;
const MAX_DESCRIPTION_BYTES: usize = 512;
const MAX_SOURCE_BYTES: u64 = 64 * 1024;
/// Maximum size accepted for a user-authored remember observation.
///
/// This matches the per-source read budget so one manually saved observation
/// cannot persist more content than v2 will inspect while building a manifest.
pub const MAX_MANUAL_OBSERVATION_BYTES: usize = MAX_SOURCE_BYTES as usize;

const EMPTY_MANIFEST: &str = "# Memory index\n\n\
> Generated by Grok. Do not edit this file directly.\n\n\
No memory files have been recorded yet.\n";

pub type Result<T> = std::result::Result<T, V2StorageError>;

#[derive(Debug, thiserror::Error)]
pub enum V2StorageError {
    #[error("failed to {operation} at {path}")]
    Io {
        operation: &'static str,
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to initialize {database} database at {path}")]
    Database {
        database: &'static str,
        path: PathBuf,
        #[source]
        source: rusqlite::Error,
    },
    #[error("v2 memory directory {path} exceeds the {limit}-entry safety limit")]
    TooManyEntries { path: PathBuf, limit: usize },
    #[error("memory observation is {actual_bytes} bytes, exceeding the {limit_bytes}-byte limit")]
    ObservationTooLarge {
        actual_bytes: usize,
        limit_bytes: usize,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum V2MemoryScope {
    Global,
    Workspace,
}

impl V2MemoryScope {
    fn heading(self) -> &'static str {
        match self {
            Self::Global => "Global memory index",
            Self::Workspace => "Workspace memory index",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct V2ManifestBudget {
    pub max_bytes: usize,
    pub max_entries: usize,
    pub max_description_bytes: usize,
}

impl Default for V2ManifestBudget {
    fn default() -> Self {
        Self {
            // Entries carry absolute paths (~60-80 bytes of prefix each), so
            // 8 KiB keeps roughly the same entry capacity a 4 KiB relative
            // manifest had.
            max_bytes: 8 * 1024,
            max_entries: 64,
            max_description_bytes: 200,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct V2Manifest {
    pub content: String,
    pub discovered_entries: usize,
    pub included_entries: usize,
    pub is_truncated: bool,
}

/// Create one v2 scope without consulting any legacy path.
///
/// # Errors
///
/// Returns [`V2StorageError::Io`] when directories or the initial manifest
/// cannot be created, and [`V2StorageError::Database`] when either SQLite
/// database cannot be initialized.
pub fn ensure_scope_initialized(
    storage_root: &Path,
    scope_dir: &Path,
    scope: V2MemoryScope,
) -> Result<()> {
    reject_symlink_components(storage_root, scope_dir)?;
    for relative in ["topics", "observations", "observations/_inbox", "archive"] {
        let path = scope_dir.join(relative);
        reject_symlink(&path, "initialize symlinked v2 memory directory")?;
        std::fs::create_dir_all(&path).map_err(|source| V2StorageError::Io {
            operation: "create v2 memory directory",
            path,
            source,
        })?;
    }
    ensure_canonical_descendant(
        storage_root,
        scope_dir,
        "validate v2 memory scope containment",
    )?;

    let state_path = scope_dir.join("memory_state.sqlite");
    reject_symlink_components(storage_root, scope_dir)?;
    reject_symlink(&state_path, "initialize symlinked v2 state database")?;
    initialize_state_db(&state_path)?;
    let index_path = scope_dir.join("index.sqlite");
    reject_symlink_components(storage_root, scope_dir)?;
    reject_symlink(&index_path, "initialize symlinked v2 lexical index")?;
    initialize_lexical_index(&index_path)?;

    let manifest_path = scope_dir.join("MEMORY.md");
    reject_symlink_components(storage_root, scope_dir)?;
    reject_symlink(&manifest_path, "initialize symlinked v2 manifest")?;
    regenerate_scope_manifest(scope_dir, scope, V2ManifestBudget::default())?;
    Ok(())
}

/// Atomically publish one immutable observation into a v2 scope inbox.
///
/// The caller must initialize the scope first. The next scope initialization
/// regenerates `MEMORY.md`; direct browse sees the observation immediately.
///
/// # Errors
///
/// Returns [`V2StorageError::ObservationTooLarge`] when `content` exceeds
/// [`MAX_MANUAL_OBSERVATION_BYTES`], or [`V2StorageError::Io`] if the inbox is
/// missing or unsafe or the observation cannot be durably published.
pub(crate) fn persist_observation(scope_dir: &Path, content: &str) -> Result<PathBuf> {
    if content.len() > MAX_MANUAL_OBSERVATION_BYTES {
        return Err(V2StorageError::ObservationTooLarge {
            actual_bytes: content.len(),
            limit_bytes: MAX_MANUAL_OBSERVATION_BYTES,
        });
    }

    let inbox = scope_dir.join("observations/_inbox");
    reject_symlink_components(scope_dir, &inbox)?;
    ensure_canonical_descendant(
        scope_dir,
        &inbox,
        "validate v2 observation inbox containment",
    )?;

    let mut temporary = tempfile::Builder::new()
        .prefix(".remember-")
        .suffix(".tmp")
        .tempfile_in(&inbox)
        .map_err(|source| V2StorageError::Io {
            operation: "create temporary v2 observation",
            path: inbox.clone(),
            source,
        })?;
    temporary
        .write_all(content.as_bytes())
        .and_then(|()| temporary.as_file().sync_all())
        .map_err(|source| V2StorageError::Io {
            operation: "write temporary v2 observation",
            path: temporary.path().to_path_buf(),
            source,
        })?;

    let temporary_name = temporary
        .path()
        .file_stem()
        .and_then(|name| name.to_str())
        .ok_or_else(|| V2StorageError::Io {
            operation: "derive v2 observation filename",
            path: temporary.path().to_path_buf(),
            source: std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "temporary observation filename is not valid UTF-8",
            ),
        })?;
    let observation_path = inbox.join(format!("{}.md", temporary_name.trim_start_matches('.')));
    temporary
        .persist_noclobber(&observation_path)
        .map_err(|error| V2StorageError::Io {
            operation: "publish v2 observation",
            path: observation_path.clone(),
            source: error.error,
        })?;
    Ok(observation_path)
}

fn reject_symlink_components(storage_root: &Path, scope_dir: &Path) -> Result<()> {
    let relative = scope_dir
        .strip_prefix(storage_root)
        .map_err(|_| V2StorageError::Io {
            operation: "validate v2 memory scope root",
            path: scope_dir.to_path_buf(),
            source: std::io::Error::new(
                std::io::ErrorKind::PermissionDenied,
                "scope is outside the configured v2 storage root",
            ),
        })?;
    reject_symlink(storage_root, "initialize symlinked v2 memory root")?;
    let mut current = storage_root.to_path_buf();
    for component in relative.components() {
        current.push(component);
        reject_symlink(&current, "initialize symlinked v2 memory path")?;
    }
    Ok(())
}

fn reject_symlink(path: &Path, operation: &'static str) -> Result<()> {
    match std::fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() => Err(V2StorageError::Io {
            operation,
            path: path.to_path_buf(),
            source: std::io::Error::new(
                std::io::ErrorKind::PermissionDenied,
                "symbolic links are not allowed",
            ),
        }),
        Ok(_) => Ok(()),
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(source) => Err(V2StorageError::Io {
            operation: "inspect v2 memory path",
            path: path.to_path_buf(),
            source,
        }),
    }
}

fn ensure_canonical_descendant(root: &Path, target: &Path, operation: &'static str) -> Result<()> {
    let canonical_root = dunce::canonicalize(root).map_err(|source| V2StorageError::Io {
        operation,
        path: root.to_path_buf(),
        source,
    })?;
    let canonical_target = dunce::canonicalize(target).map_err(|source| V2StorageError::Io {
        operation,
        path: target.to_path_buf(),
        source,
    })?;
    if canonical_target.starts_with(&canonical_root) {
        Ok(())
    } else {
        Err(V2StorageError::Io {
            operation,
            path: target.to_path_buf(),
            source: std::io::Error::new(
                std::io::ErrorKind::PermissionDenied,
                "path escapes the configured v2 storage root",
            ),
        })
    }
}

/// Rebuild a scope's generated `MEMORY.md` with an atomic replacement.
///
/// # Errors
///
/// Returns [`V2StorageError::Io`] if source files cannot be enumerated or the
/// replacement cannot be persisted.
pub fn regenerate_scope_manifest(
    scope_dir: &Path,
    scope: V2MemoryScope,
    budget: V2ManifestBudget,
) -> Result<V2Manifest> {
    let manifest = render_scope_manifest(scope_dir, scope, budget)?;
    persist_scope_manifest(scope_dir, &manifest)?;
    Ok(manifest)
}

pub(crate) fn persist_scope_manifest(scope_dir: &Path, manifest: &V2Manifest) -> Result<()> {
    persist_replacing_file(&scope_dir.join("MEMORY.md"), manifest.content.as_bytes())
}

/// Render a deterministic, bounded pointer index for one memory scope.
///
/// # Errors
///
/// Returns [`V2StorageError::Io`] if a source directory cannot be enumerated.
pub fn render_scope_manifest(
    scope_dir: &Path,
    scope: V2MemoryScope,
    budget: V2ManifestBudget,
) -> Result<V2Manifest> {
    reject_symlink(scope_dir, "render symlinked v2 memory scope")?;
    let budget = V2ManifestBudget {
        max_bytes: budget.max_bytes.min(MAX_MANIFEST_BYTES),
        max_entries: budget.max_entries.min(MAX_MANIFEST_ENTRIES),
        max_description_bytes: budget.max_description_bytes.min(MAX_DESCRIPTION_BYTES),
    };
    let (mut entries, discovered_entries) =
        collect_entries(scope_dir, budget.max_description_bytes)?;
    entries.sort_by(|left, right| {
        left.kind
            .cmp(&right.kind)
            .then_with(|| left.relative_path.cmp(&right.relative_path))
    });

    let selected_entries = entries.into_iter().take(budget.max_entries);
    let header = format!(
        "# {}\n\n> Generated by Grok. Do not edit this file directly.\n",
        scope.heading()
    );
    let mut content = truncate_str(&header, budget.max_bytes).to_owned();
    let was_header_limited = content.len() < header.len();
    let mut current_kind = None;
    let mut included_entries = 0;
    let mut was_byte_limited = was_header_limited;
    if !was_header_limited {
        for entry in selected_entries {
            let mut addition = String::new();
            if current_kind != Some(entry.kind) {
                addition.push_str(match entry.kind {
                    ManifestEntryKind::Topic => "\n## Topics\n",
                    ManifestEntryKind::Observation => "\n## Pending observations\n",
                });
            }
            addition.push_str("\n- **");
            addition.push_str(&entry.title);
            addition.push_str("**");
            if !entry.description.is_empty() {
                addition.push_str(" — ");
                addition.push_str(&entry.description);
            }
            // Absolute paths so the model never has to join a relative entry
            // onto the scope root (and cannot mistake the legacy memory root).
            addition.push_str(" (`");
            addition.push_str(&scope_dir.join(&entry.relative_path).display().to_string());
            addition.push_str("`)\n");
            if content.len().saturating_add(addition.len()) > budget.max_bytes {
                was_byte_limited = true;
                continue;
            }
            content.push_str(&addition);
            current_kind = Some(entry.kind);
            included_entries += 1;
        }
    }

    if discovered_entries == 0 {
        let empty = EMPTY_MANIFEST.replacen("Memory index", scope.heading(), 1);
        content = truncate_str(&empty, budget.max_bytes).to_owned();
        was_byte_limited = content.len() < empty.len();
    }

    let was_entry_limited = discovered_entries > included_entries;

    Ok(V2Manifest {
        content,
        discovered_entries,
        included_entries,
        is_truncated: was_entry_limited || was_byte_limited,
    })
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum ManifestEntryKind {
    Topic,
    Observation,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ManifestEntry {
    kind: ManifestEntryKind,
    relative_path: String,
    title: String,
    description: String,
}

fn collect_entries(
    scope_dir: &Path,
    max_description_bytes: usize,
) -> Result<(Vec<ManifestEntry>, usize)> {
    let mut entries = Vec::new();
    let mut discovered_entries = collect_entries_from(
        scope_dir,
        Path::new("topics"),
        ManifestEntryKind::Topic,
        max_description_bytes,
        &mut entries,
    )?;
    discovered_entries += collect_entries_from(
        scope_dir,
        Path::new("observations/_inbox"),
        ManifestEntryKind::Observation,
        max_description_bytes,
        &mut entries,
    )?;
    Ok((entries, discovered_entries))
}

fn collect_entries_from(
    scope_dir: &Path,
    relative_dir: &Path,
    kind: ManifestEntryKind,
    max_description_bytes: usize,
    entries: &mut Vec<ManifestEntry>,
) -> Result<usize> {
    let directory = scope_dir.join(relative_dir);
    reject_symlink(&directory, "read symlinked v2 memory directory")?;
    if directory.exists() {
        ensure_canonical_descendant(
            scope_dir,
            &directory,
            "validate v2 manifest source containment",
        )?;
    }
    let read_dir = match std::fs::read_dir(&directory) {
        Ok(read_dir) => read_dir,
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => return Ok(0),
        Err(source) => {
            return Err(V2StorageError::Io {
                operation: "enumerate v2 memory files",
                path: directory,
                source,
            });
        }
    };

    let remaining = MAX_DISCOVERED_FILES.saturating_sub(entries.len());
    let mut candidates = Vec::new();
    for (entry_index, entry) in read_dir.enumerate() {
        if entry_index >= MAX_DIRECTORY_ENTRIES {
            return Err(V2StorageError::TooManyEntries {
                path: directory,
                limit: MAX_DIRECTORY_ENTRIES,
            });
        }
        let entry = match entry {
            Ok(entry) => entry,
            Err(source) => {
                return Err(V2StorageError::Io {
                    operation: "read v2 memory directory entry",
                    path: directory.clone(),
                    source,
                });
            }
        };
        let path = entry.path();
        let file_type = entry.file_type().map_err(|source| V2StorageError::Io {
            operation: "inspect v2 memory entry",
            path: path.clone(),
            source,
        })?;
        if !file_type.is_file() || path.extension().and_then(|value| value.to_str()) != Some("md") {
            continue;
        }

        let relative_path = match path.strip_prefix(scope_dir) {
            Ok(relative) => relative.to_string_lossy().replace('\\', "/"),
            Err(_) => continue,
        };
        candidates.push((relative_path, path));
    }
    candidates.sort_by(|left, right| left.0.cmp(&right.0));

    let discovered_entries = candidates.len();
    for (relative_path, path) in candidates.into_iter().take(remaining) {
        let (title, description) =
            summarize_file(&path, max_description_bytes).unwrap_or_else(|_| {
                let title = path
                    .file_stem()
                    .and_then(|value| value.to_str())
                    .unwrap_or("memory")
                    .to_owned();
                (title, String::new())
            });
        entries.push(ManifestEntry {
            kind,
            relative_path: sanitize_inline(&relative_path),
            title: sanitize_inline(truncate_str(&title, MAX_DESCRIPTION_BYTES)),
            description: sanitize_inline(&description),
        });
    }
    Ok(discovered_entries)
}

fn summarize_file(path: &Path, max_description_bytes: usize) -> std::io::Result<(String, String)> {
    let mut file = std::fs::File::open(path)?;
    let mut bytes = Vec::new();
    std::io::Read::by_ref(&mut file)
        .take(MAX_SOURCE_BYTES)
        .read_to_end(&mut bytes)?;
    let body = String::from_utf8_lossy(&bytes);
    let mut title = None;
    let mut description = None;

    for line in body.lines().map(str::trim).filter(|line| !line.is_empty()) {
        if title.is_none() && line.starts_with('#') {
            let heading = line.trim_start_matches('#').trim();
            if !heading.is_empty() {
                title = Some(heading.to_owned());
            }
            continue;
        }
        if description.is_none()
            && !line.starts_with('#')
            && !line.starts_with("<!--")
            && !line.starts_with('>')
        {
            description = Some(truncate_str(line, max_description_bytes).to_owned());
        }
        if title.is_some() && description.is_some() {
            break;
        }
    }

    let fallback_title = path
        .file_stem()
        .and_then(|value| value.to_str())
        .unwrap_or("memory")
        .to_owned();
    Ok((
        title.unwrap_or(fallback_title),
        description.unwrap_or_default(),
    ))
}

fn sanitize_inline(value: &str) -> String {
    value
        .chars()
        .map(|character| match character {
            '\n' | '\r' => ' ',
            '`' => '\'',
            _ => character,
        })
        .collect()
}

fn initialize_state_db(path: &Path) -> Result<()> {
    let connection = JournalMode::for_db_path(path)
        .open(path)
        .map_err(|source| V2StorageError::Database {
            database: "state",
            path: path.to_path_buf(),
            source,
        })?;
    connection
        .execute_batch(
            "CREATE TABLE IF NOT EXISTS meta (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
            );",
        )
        .and_then(|_| {
            connection.execute(
                "INSERT OR IGNORE INTO meta(key, value) VALUES ('schema_version', ?1)",
                params![STATE_SCHEMA_VERSION],
            )
        })
        .map(|_| ())
        .map_err(|source| V2StorageError::Database {
            database: "state",
            path: path.to_path_buf(),
            source,
        })
}

fn initialize_lexical_index(path: &Path) -> Result<()> {
    let connection = JournalMode::for_db_path(path)
        .open(path)
        .map_err(|source| V2StorageError::Database {
            database: "lexical index",
            path: path.to_path_buf(),
            source,
        })?;
    connection
        .execute_batch(&crate::schema::schema_sql(1, false))
        .and_then(|_| {
            connection.execute(
                crate::schema::UPSERT_META_SQL,
                params!["retrieval_mode", "fts_only"],
            )
        })
        .map(|_| ())
        .map_err(|source| V2StorageError::Database {
            database: "lexical index",
            path: path.to_path_buf(),
            source,
        })
}

fn persist_replacing_file(path: &Path, contents: &[u8]) -> Result<()> {
    let parent = path.parent().ok_or_else(|| V2StorageError::Io {
        operation: "resolve v2 manifest parent",
        path: path.to_path_buf(),
        source: std::io::Error::new(std::io::ErrorKind::InvalidInput, "path has no parent"),
    })?;
    std::fs::create_dir_all(parent).map_err(|source| V2StorageError::Io {
        operation: "create v2 manifest parent",
        path: parent.to_path_buf(),
        source,
    })?;
    let mut temporary =
        tempfile::NamedTempFile::new_in(parent).map_err(|source| V2StorageError::Io {
            operation: "create temporary v2 manifest",
            path: path.to_path_buf(),
            source,
        })?;
    temporary
        .write_all(contents)
        .and_then(|()| temporary.as_file().sync_all())
        .map_err(|source| V2StorageError::Io {
            operation: "write temporary v2 manifest",
            path: path.to_path_buf(),
            source,
        })?;
    temporary
        .persist(path)
        .map(|_| ())
        .map_err(|error| V2StorageError::Io {
            operation: "publish v2 manifest",
            path: path.to_path_buf(),
            source: error.error,
        })
}

#[cfg(test)]
#[path = "v2_tests.rs"]
mod tests;
