use std::fs;
use std::path::PathBuf;

use rusqlite::params;
use tempfile::TempDir;
use xai_sqlite_journal::JournalMode;

use super::*;
use crate::v2::{V2ManifestBudget, ensure_scope_initialized, render_scope_manifest};
use crate::v2_maintenance::{ForgetReason, ForgetRequest, V2MaintenanceStore};

#[derive(Debug)]
struct FixedClock(i64);

impl V2Clock for FixedClock {
    fn now_unix_seconds(&self) -> i64 {
        self.0
    }
}

struct Fixture {
    _temp: TempDir,
    source: PathBuf,
    global: PathBuf,
    workspace: PathBuf,
    policy: V2MemoryAccessPolicy,
}

impl Fixture {
    fn new() -> Self {
        let temp = TempDir::new().unwrap();
        let root = temp.path().join("memory-v2");
        let legacy_root = temp.path().join("memory");
        let global = root.join("global");
        let workspace = root.join("workspaces/repo-50aa78f0");
        fs::create_dir_all(&root).unwrap();
        fs::create_dir_all(legacy_root.join("repo-50aa78f0")).unwrap();
        ensure_scope_initialized(&root, &global, V2MemoryScope::Global).unwrap();
        ensure_scope_initialized(&root, &workspace, V2MemoryScope::Workspace).unwrap();
        let policy = V2MemoryAccessPolicy::new(&global, &workspace).unwrap();
        Self {
            _temp: temp,
            source: legacy_memory_file(&legacy_root, V2MemoryScope::Workspace, "repo-50aa78f0"),
            global,
            workspace,
            policy,
        }
    }

    fn write_legacy(&self, content: &str) {
        fs::write(&self.source, content).unwrap();
    }

    fn run(&self) -> Result<V2CarryoverOutcome> {
        carry_over_legacy_memory(
            &self.workspace,
            &self.source,
            &self.policy,
            &FixedClock(1_760_000_000),
        )
    }

    fn run_imported(&self) -> V2CarryoverReport {
        match self.run().unwrap() {
            V2CarryoverOutcome::Imported(report) => report,
            other => panic!("expected import, got {other:?}"),
        }
    }

    fn topic(&self, slug: &str) -> String {
        fs::read_to_string(self.workspace.join(format!("topics/{slug}.md"))).unwrap()
    }

    fn topic_names(&self) -> Vec<String> {
        let mut names: Vec<String> = fs::read_dir(self.workspace.join("topics"))
            .unwrap()
            .map(|entry| entry.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        names.sort();
        names
    }

    fn meta(&self, key: &str) -> Option<String> {
        let path = self.workspace.join("memory_state.sqlite");
        let connection = JournalMode::for_db_path(&path).open(&path).unwrap();
        connection
            .query_row(
                "SELECT value FROM meta WHERE key = ?1",
                params![key],
                |row| row.get(0),
            )
            .ok()
    }

    fn manifest(&self) -> crate::v2::V2Manifest {
        render_scope_manifest(
            &self.workspace,
            V2MemoryScope::Workspace,
            V2ManifestBudget::default(),
        )
        .unwrap()
    }
}

const DREAM_SHAPED: &str = "# Project Memory — repo

> Auto-populated by dream consolidation. Edit freely.

## Identity and PR lookup

The reviewer bot's login is `review-bot`. A name search does not find its PRs.

### Query

Use `author:review-bot` on `org/repo`.

## Build & Test

Run `cargo test -p xai-grok-memory`. Clippy must pass.

```sh
# not a heading
cargo clippy
```

Bazel BUILD files are generated by Gazelle, never edited by hand, and CI runs
`just gazelle --check` on every PR, so run it locally before pushing any change
that adds, renames, or deletes a source file inside an existing crate.
";

#[test]
fn missing_or_scaffold_sources_leave_the_scope_untouched() {
    let fixture = Fixture::new();
    assert_eq!(V2CarryoverOutcome::MissingSource, fixture.run().unwrap());

    fixture.write_legacy(
        "# Project Memory — repo\n\n> Auto-populated by dream consolidation. Edit freely.\n",
    );
    assert_eq!(V2CarryoverOutcome::NothingToCarry, fixture.run().unwrap());
    fixture.write_legacy(
        "# Global Memory\n\n> managed\n\n## Preferences\n\n<!-- Add any cross-project preferences here -->\n",
    );
    assert_eq!(V2CarryoverOutcome::NothingToCarry, fixture.run().unwrap());

    assert!(fixture.topic_names().is_empty());
    assert_eq!(None, fixture.meta(META_HASH_KEY));
}

#[test]
fn short_file_that_still_carries_the_scaffold_marker_is_imported() {
    let fixture = Fixture::new();
    fixture.write_legacy(
        "# Global Memory\n\n> Auto-populated by dream consolidation. Edit freely.\n\n## Preferences\n\n- Prefer short answers.\n",
    );
    assert_eq!(1, fixture.run_imported().topics_created);
    assert_eq!(
        "# Preferences\nPrefer short answers.\n\n- Prefer short answers.\n",
        fixture.topic("preferences")
    );
}

#[test]
fn dream_shaped_file_splits_into_one_topic_per_section() {
    let fixture = Fixture::new();
    fixture.write_legacy(DREAM_SHAPED);

    let report = fixture.run_imported();
    assert_eq!(
        V2CarryoverReport {
            topics_created: 2,
            topics_appended: 0,
            sections_skipped: 0,
            bytes_written: (fixture.topic("identity-and-pr-lookup").len()
                + fixture.topic("build-test").len()) as u64,
        },
        report
    );
    assert_eq!(
        "# Identity and PR lookup\nThe reviewer bot's login is `review-bot`.\n\n\
         The reviewer bot's login is `review-bot`. A name search does not find its PRs.\n\n\
         ## Query\n\nUse `author:review-bot` on `org/repo`.\n",
        fixture.topic("identity-and-pr-lookup")
    );
    let build = fixture.topic("build-test");
    assert!(build.starts_with("# Build & Test\nRun `cargo test -p xai-grok-memory`.\n\n"));
    assert!(
        build.contains("\n# not a heading\n"),
        "fenced text is copied verbatim"
    );
    assert_eq!(DREAM_SHAPED, fs::read_to_string(&fixture.source).unwrap());
    assert_eq!(
        Some(blake3::hash(DREAM_SHAPED.as_bytes()).to_hex().to_string()),
        fixture.meta(META_HASH_KEY)
    );
    assert_eq!(Some("1760000000".to_owned()), fixture.meta(META_AT_KEY));
    assert!(fixture.manifest().content.contains(
        "- **Identity and PR lookup** — The reviewer bot's login is 'review-bot'. (`topics/identity-and-pr-lookup.md`)"
    ));
}

#[test]
fn unchanged_source_is_a_no_op_and_a_changed_source_imports_only_the_delta() {
    let fixture = Fixture::new();
    fixture.write_legacy(DREAM_SHAPED);
    fixture.run_imported();
    let first = fixture.topic("build-test");

    assert_eq!(V2CarryoverOutcome::Unchanged, fixture.run().unwrap());
    assert_eq!(first, fixture.topic("build-test"));

    fixture.write_legacy(&format!(
        "{DREAM_SHAPED}\n## Build & Test\n\nAlso run `cargo fmt --all`.\n\n## Releases\n\nAlpha is `grok update --alpha`.\n"
    ));
    let report = fixture.run_imported();
    assert_eq!(1, report.topics_created, "Releases is new");
    assert_eq!(1, report.topics_appended, "Build & Test gained a paragraph");
    assert_eq!(1, report.sections_skipped, "Identity is present verbatim");
    let build = fixture.topic("build-test");
    assert!(build.starts_with(first.trim_end()));
    assert!(build.ends_with("\n\n## From earlier sessions\n\nAlso run `cargo fmt --all`.\n"));
    assert_eq!(
        vec!["build-test.md", "identity-and-pr-lookup.md", "releases.md"],
        fixture.topic_names()
    );
}

#[test]
fn existing_v2_topic_keeps_its_content_first_and_demotes_appended_headings() {
    let fixture = Fixture::new();
    let existing = "# Build & Test\nHow the crate is built.\n\n## Commands\n- `cargo test`\n";
    fs::write(fixture.workspace.join("topics/build-test.md"), existing).unwrap();
    fixture.write_legacy(DREAM_SHAPED);

    let report = fixture.run_imported();
    assert_eq!((1, 1), (report.topics_created, report.topics_appended));
    let merged = fixture.topic("build-test");
    let appended = merged
        .strip_prefix(existing.trim_end())
        .expect("existing content stays first");
    assert!(
        appended
            .starts_with("\n\n## From earlier sessions\n\nRun `cargo test -p xai-grok-memory`.")
    );
    assert_eq!(
        1,
        appended.matches("\n## ").count(),
        "appended headings sit below the section heading"
    );
}

#[test]
fn paragraph_dedupe_compares_whole_paragraphs() {
    let fixture = Fixture::new();
    fs::write(
        fixture.workspace.join("topics/build.md"),
        "# Build\nHow to build.\n\nRun cargo build, then cargo test.\n",
    )
    .unwrap();
    fixture.write_legacy("# Project Memory\n\n## Build\n\nRun cargo build\n");

    assert_eq!(1, fixture.run_imported().topics_appended);
    assert!(
        fixture
            .topic("build")
            .ends_with("## From earlier sessions\n\nRun cargo build\n")
    );
}

#[test]
fn append_that_would_exceed_the_topic_cap_is_skipped() {
    let fixture = Fixture::new();
    let existing = format!("# Big\nLarge topic.\n\n{}\n", "x".repeat(256 * 1024 - 64));
    fs::write(fixture.workspace.join("topics/big.md"), &existing).unwrap();
    fixture
        .write_legacy("# Project Memory\n\n## Big\n\nMore about big things that will not fit.\n");

    let report = fixture.run_imported();
    assert_eq!((0, 1), (report.topics_appended, report.sections_skipped));
    assert_eq!(existing, fixture.topic("big"));
}

#[test]
fn tombstoned_topic_name_is_not_recreated() {
    let fixture = Fixture::new();
    let path = fixture.workspace.join("topics/build-test.md");
    fs::write(&path, "# Build & Test\nOld.\n").unwrap();
    V2MaintenanceStore::open_with_clock(
        &fixture.workspace,
        V2MemoryScope::Workspace,
        &fixture.global,
        &fixture.workspace,
        std::sync::Arc::new(FixedClock(1)),
    )
    .unwrap()
    .forget(&ForgetRequest {
        relative_path: PathBuf::from("topics/build-test.md"),
        expected_content_hash: blake3::hash(b"# Build & Test\nOld.\n").to_hex().to_string(),
        reason: ForgetReason::UserRequest,
        now: 1,
    })
    .unwrap();
    fixture.write_legacy(DREAM_SHAPED);

    let report = fixture.run_imported();
    assert_eq!((1, 1), (report.topics_created, report.sections_skipped));
    assert!(!path.exists());
    assert!(
        fixture.meta(META_HASH_KEY).is_some(),
        "a tombstone is a deterministic skip, so the import is complete"
    );
    assert_eq!(V2CarryoverOutcome::Unchanged, fixture.run().unwrap());
}

#[test]
fn hand_curated_outline_splits_on_top_level_headings() {
    let fixture = Fixture::new();
    fixture.write_legacy(
        "# Global Memory\n\n# Identity\n\nI work on the Developer org.\n\n## Role\n\nLead.\n\n# People\n\nThe team lead owns Grok Build.\n",
    );
    assert_eq!(2, fixture.run_imported().topics_created);
    assert_eq!(
        "# Identity\nI work on the Developer org.\n\nI work on the Developer org.\n\n## Role\n\nLead.\n",
        fixture.topic("identity")
    );
    assert!(
        fixture
            .topic("people")
            .starts_with("# People\nThe team lead owns Grok Build.\n")
    );
}

#[test]
fn file_without_headings_becomes_a_single_topic() {
    let fixture = Fixture::new();
    fixture.write_legacy("# Global Memory\n\n- Prefer short answers.\n- Never use emoji.\n");
    assert_eq!(1, fixture.run_imported().topics_created);
    assert_eq!(
        "# Global Memory\nPrefer short answers.\n\n- Prefer short answers.\n- Never use emoji.\n",
        fixture.topic("global-memory")
    );
}

#[test]
fn preamble_with_real_content_becomes_an_overview_topic() {
    let fixture = Fixture::new();
    fixture.write_legacy(
        "# Project Memory — repo\n\n> managed\n\nThe repo is a monorepo rooted at /src/repo.\n\n## Build\n\nUse cargo.\n",
    );
    assert_eq!(2, fixture.run_imported().topics_created);
    assert_eq!(vec!["build.md", "overview.md"], fixture.topic_names());
    assert!(
        fixture
            .topic("overview")
            .starts_with("# Overview\nThe repo is a monorepo rooted at /src/repo.\n")
    );
}

#[test]
fn duplicate_section_titles_merge_into_one_topic() {
    let fixture = Fixture::new();
    fixture.write_legacy("# Project Memory\n\n## Build\n\nOne.\n\n## Build\n\nTwo.\n");
    assert_eq!(1, fixture.run_imported().topics_created);
    assert_eq!("# Build\nOne.\n\nOne.\n\nTwo.\n", fixture.topic("build"));
}

#[test]
fn sections_beyond_the_cap_fold_into_one_topic_and_the_index_stays_bounded() {
    let fixture = Fixture::new();
    let mut content = String::from("# Project Memory — repo\n\n");
    for index in 0..40 {
        content.push_str(&format!(
            "## Topic {index}\n\nFact number {index} about the project.\n\n### Detail\n\nMore on {index}.\n\n"
        ));
    }
    fixture.write_legacy(&content);

    assert_eq!(25, fixture.run_imported().topics_created);
    let folded = fixture.topic("more-notes");
    assert!(folded.starts_with("# More notes\n"));
    assert!(folded.contains("\n## Topic 24\n\nFact number 24 about the project.\n\n### Detail\n"));
    assert!(folded.contains("\n## Topic 39\n"));
    let manifest = fixture.manifest();
    assert_eq!(25, manifest.included_entries);
    assert!(!manifest.is_truncated);
}

#[test]
fn oversized_non_ascii_section_is_truncated_on_a_char_boundary() {
    let fixture = Fixture::new();
    let paragraph = format!("{}\n\n", "é".repeat(4_000));
    fixture.write_legacy(&format!(
        "# Project Memory\n\n## Big\n\nIntro.\n\n{}",
        paragraph.repeat(40)
    ));
    assert_eq!(1, fixture.run_imported().topics_created);
    let topic = fixture.topic("big");
    assert!(topic.len() as u64 <= MAX_TOPIC_FILE_BYTES);
    assert!(topic.starts_with("# Big\nIntro.\n\nIntro.\n\né"));
    assert!(topic.ends_with("é\n"), "cut lands on a paragraph boundary");
}

#[test]
fn write_failure_leaves_the_hash_unrecorded_so_the_next_start_retries() {
    let fixture = Fixture::new();
    fixture.write_legacy(DREAM_SHAPED);
    // A directory where the topic file belongs fails the read and the write
    // for any user, unlike a permission bit, which root ignores.
    let blocker = fixture.workspace.join("topics/build-test.md");
    fs::create_dir(&blocker).unwrap();

    let report = fixture.run_imported();
    assert_eq!((1, 1), (report.topics_created, report.sections_skipped));
    assert_eq!(
        None,
        fixture.meta(META_HASH_KEY),
        "a write error must not finalize"
    );

    fs::remove_dir(&blocker).unwrap();
    let report = fixture.run_imported();
    assert_eq!(
        (1, 1),
        (report.topics_created, report.sections_skipped),
        "retry writes the failed section and skips the one already present"
    );
    assert!(fixture.meta(META_HASH_KEY).is_some());
    assert_eq!(V2CarryoverOutcome::Unchanged, fixture.run().unwrap());
}

#[test]
fn oversized_source_is_rejected() {
    let fixture = Fixture::new();
    fixture.write_legacy(&"y".repeat((MAX_SOURCE_BYTES + 1) as usize));
    assert!(matches!(
        fixture.run().unwrap_err(),
        V2CarryoverError::SourceTooLarge { .. }
    ));
    assert!(fixture.topic_names().is_empty());
}
